# Project 3: SQL Data Analysis

In [4]:
import sqlite3
import pandas as pd

In [7]:
# 1. Loaded my cleaned dataset from Project 1
df = pd.read_csv("C:/Users/User/Desktop/DecodeLabs DA Internship/Cleaned_Sales_Data.csv")

In [8]:
# 2. Created a connection to a local SQL database 
conn = sqlite3.connect('ecommerce.db')

In [9]:
# 3. Pushing the pandas DataFrame into a SQL table named 'sales_data'
df.to_sql('sales_data', conn, if_exists='replace', index=False)

1200

In [10]:
print("Database connected and table 'sales_data' created successfully!")

Database connected and table 'sales_data' created successfully!

In [11]:
query1 = """
SELECT OrderID, Date, Product, TotalPrice 
FROM sales_data 
WHERE OrderStatus = 'Delivered' AND TotalPrice > 1000
ORDER BY TotalPrice DESC;
"""

# Executing the query against my database connection
high_value_deliveries = pd.read_sql_query(query1, conn)

# Display the results
high_value_deliveries

      OrderID        Date  Product  TotalPrice
0   ORD200789  2023-08-17   Tablet     3456.40
1   ORD200632  2023-05-02   Laptop     3390.80
2   ORD201065  2023-10-30  Printer     3334.00
3   ORD200361  2024-06-29  Printer     3299.25
4   ORD200837  2025-06-14    Chair     3277.75
..        ...         ...      ...         ...
86  ORD201116  2023-10-14  Printer     1062.98
87  ORD201092  2023-08-21   Laptop     1046.00
88  ORD200939  2025-04-16   Laptop     1042.80
89  ORD201098  2023-06-17  Monitor     1023.44
90  ORD200589  2025-02-10   Laptop     1001.60

[91 rows x 4 columns]

In [12]:
query2 = """
SELECT 
    Product, 
    COUNT(OrderID) AS Total_Orders, 
    ROUND(AVG(TotalPrice), 2) AS Avg_Order_Value, 
    ROUND(SUM(TotalPrice), 2) AS Total_Revenue
FROM sales_data
GROUP BY Product
ORDER BY Total_Revenue DESC;
"""

# Executing the query
product_summary = pd.read_sql_query(query2, conn)

# Displaying the results
product_summary

   Product  Total_Orders  Avg_Order_Value  Total_Revenue
0    Chair           178          1098.99      195620.11
1  Printer           181          1080.73      195612.61
2   Laptop           173          1110.56      192126.56
3   Tablet           179          1042.28      186568.95
4  Monitor           163          1077.62      175651.41
5     Desk           170           985.06      167459.93
6    Phone           156           972.58      151722.39

In [13]:
# Closing the connection so i can free up memory
conn.close()